//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace TesttoolConfigurationEditor {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class TesttoolConfig {
        
        private TesttoolConfigSoftwareVersion softwareVersionField;
        
        private TesttoolConfigDebugging debuggingField;
        
        private TesttoolConfigSupportedTransferSyntaxes supportedTransferSyntaxesField;
        
        private TesttoolConfigApplicationEntityConfiguration applicationEntityConfigurationField;
        
        /// <remarks/>
        public TesttoolConfigSoftwareVersion SoftwareVersion {
            get {
                return this.softwareVersionField;
            }
            set {
                this.softwareVersionField = value;
            }
        }
        
        /// <remarks/>
        public TesttoolConfigDebugging Debugging {
            get {
                return this.debuggingField;
            }
            set {
                this.debuggingField = value;
            }
        }
        
        /// <remarks/>
        public TesttoolConfigSupportedTransferSyntaxes SupportedTransferSyntaxes {
            get {
                return this.supportedTransferSyntaxesField;
            }
            set {
                this.supportedTransferSyntaxesField = value;
            }
        }
        
        /// <remarks/>
        public TesttoolConfigApplicationEntityConfiguration ApplicationEntityConfiguration {
            get {
                return this.applicationEntityConfigurationField;
            }
            set {
                this.applicationEntityConfigurationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TesttoolConfigSoftwareVersion {
        
        private int majorField;
        
        private int minorField;
        
        /// <remarks/>
        public int Major {
            get {
                return this.majorField;
            }
            set {
                this.majorField = value;
            }
        }
        
        /// <remarks/>
        public int Minor {
            get {
                return this.minorField;
            }
            set {
                this.minorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SUTAESetting {
        
        private string aETitleField;
        
        private int portField;
        
        private CommandConfig commandField;
        
        /// <remarks/>
        public string AETitle {
            get {
                return this.aETitleField;
            }
            set {
                this.aETitleField = value;
            }
        }
        
        /// <remarks/>
        public int Port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CommandConfig Command {
            get {
                return this.commandField;
            }
            set {
                this.commandField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    public enum CommandConfig {
        
        /// <remarks/>
        CMOVE,
        
        /// <remarks/>
        CSTORE,
        
        /// <remarks/>
        CFIND,
        
        /// <remarks/>
        UPS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SUTAEConfiguration {
        
        private string iPAddressField;
        
        private SUTAESetting[] sUTAESettingField;
        
        private SUTActor actorField;
        
        /// <remarks/>
        public string IPAddress {
            get {
                return this.iPAddressField;
            }
            set {
                this.iPAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SUTAESetting")]
        public SUTAESetting[] SUTAESetting {
            get {
                return this.sUTAESettingField;
            }
            set {
                this.sUTAESettingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SUTActor Actor {
            get {
                return this.actorField;
            }
            set {
                this.actorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    public enum SUTActor {
        
        /// <remarks/>
        PDS,
        
        /// <remarks/>
        TMS,
        
        /// <remarks/>
        OST,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DVTKAEConfiguration {
        
        private string aETitleField;
        
        private int portField;
        
        private DVTKActor actorField;
        
        private CommandConfig commandField;
        
        /// <remarks/>
        public string AETitle {
            get {
                return this.aETitleField;
            }
            set {
                this.aETitleField = value;
            }
        }
        
        /// <remarks/>
        public int Port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DVTKActor Actor {
            get {
                return this.actorField;
            }
            set {
                this.actorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CommandConfig Command {
            get {
                return this.commandField;
            }
            set {
                this.commandField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    public enum DVTKActor {
        
        /// <remarks/>
        PDS,
        
        /// <remarks/>
        TMS,
        
        /// <remarks/>
        OST,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TransferSyntax {
        
        private string valueField;
        
        private bool usedField;
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public bool Used {
            get {
                return this.usedField;
            }
            set {
                this.usedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TesttoolConfigDebugging {
        
        private bool reportDebugMessagesField;
        
        private bool doCleanUpField;
        
        private bool reportTBDRuleField;
        
        /// <remarks/>
        public bool ReportDebugMessages {
            get {
                return this.reportDebugMessagesField;
            }
            set {
                this.reportDebugMessagesField = value;
            }
        }
        
        /// <remarks/>
        public bool DoCleanUp {
            get {
                return this.doCleanUpField;
            }
            set {
                this.doCleanUpField = value;
            }
        }
        
        /// <remarks/>
        public bool ReportTBDRule {
            get {
                return this.reportTBDRuleField;
            }
            set {
                this.reportTBDRuleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TesttoolConfigSupportedTransferSyntaxes {
        
        private TransferSyntax[] senderField;
        
        private TransferSyntax[] receiverField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TransferSyntax[] Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TransferSyntax[] Receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TesttoolConfigApplicationEntityConfiguration {
        
        private DVTKAEConfiguration[] dVTKAEConfigurationField;
        
        private SUTAEConfiguration[] sUTAEConfigurationField;
        
        private string rTPlanFileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DVTKAEConfiguration")]
        public DVTKAEConfiguration[] DVTKAEConfiguration {
            get {
                return this.dVTKAEConfigurationField;
            }
            set {
                this.dVTKAEConfigurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SUTAEConfiguration")]
        public SUTAEConfiguration[] SUTAEConfiguration {
            get {
                return this.sUTAEConfigurationField;
            }
            set {
                this.sUTAEConfigurationField = value;
            }
        }
        
        /// <remarks/>
        public string RTPlanFileName {
            get {
                return this.rTPlanFileNameField;
            }
            set {
                this.rTPlanFileNameField = value;
            }
        }
    }
}
