'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.0.30319.17929.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
Partial Public Class WorkflowState
    
    Private pDSField() As WorkflowScenarioState
    
    Private tMSField() As WorkflowScenarioState
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
    Public Property PDS() As WorkflowScenarioState()
        Get
            Return Me.pDSField
        End Get
        Set
            Me.pDSField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
    Public Property TMS() As WorkflowScenarioState()
        Get
            Return Me.tMSField
        End Get
        Set
            Me.tMSField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class WorkflowScenarioState
    
    Private uPS_ScenarioField As UPS_Scenario
    
    Private executedField As Boolean
    
    '''<remarks/>
    Public Property UPS_Scenario() As UPS_Scenario
        Get
            Return Me.uPS_ScenarioField
        End Get
        Set
            Me.uPS_ScenarioField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Executed() As Boolean
        Get
            Return Me.executedField
        End Get
        Set
            Me.executedField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
 System.SerializableAttribute()>  _
Public Enum UPS_Scenario
    
    '''<remarks/>
    WorklistQuery
    
    '''<remarks/>
    UpsInProgress
    
    '''<remarks/>
    RetrieveInputObjects
    
    '''<remarks/>
    UpsProgressUpdate
    
    '''<remarks/>
    StoreResults
    
    '''<remarks/>
    UpsFinalUpdate
    
    '''<remarks/>
    UpsCompletedOrCancelled
	
	'''<remarks/>
    UpsCreate

    '''<remarks/>
    UpsGet

    '''<remarks/>
    UpsSubscribe
End Enum
